// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Inserindo chaves diretamente para garantir funcionamento imediato no Cloudflare
  const SUPABASE_URL = "https://ftalrdptjbzmpxjgbzpq.supabase.co";
  const SUPABASE_ANON_KEY = "sb_publishable_YUWyZNk8vXuVwsjBqLvmfA_Swe2363Z";

  // Removendo bloqueio de erro para garantir funcionamento
  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    console.warn("[Supabase] Variáveis não encontradas, usando fallback estático.");
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

